### ISSUE TITLE
Installation failed,  cannot find  xcsv_hires.zip

### ISSUE THREAD

**Issue by QuakeDave** [diegoulloao/ioquake3-mac-install#15]
Hello Diego! 

First of all thank you very much for your great and easy Quake 3 installer.

After a fresh install of Mojave on my MacBookPro 6,1 the installation unfortunately failed:

End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of xcsv_hires.zip or
        xcsv_hires.zip.zip, and cannot find xcsv_hires.zip.ZIP, period.

**Comment by diegoulloao** [comment]
Hi @QuakeDave, yeah, actually this is happening because the file `xcsv_hires.zip` was removed from the server:
https://ioquake3.org/files/xcsv_hires.zip

Producing an error at this line of the installer:
https://github.com/diegoulloao/ioquake3-mac-install/blob/master/install.sh#L179

I will found a solution for replace that file today.
Thanks for reporting.

**Comment by diegoulloao** [comment]
I fixed the broken link in this `dev` branch, can you try now?
https://github.com/diegoulloao/ioquake3-mac-install/tree/dev

If all works, I'll merge it to `master`

**Comment by QuakeDave** [comment]
Thanks for the quick reply!

The install code is still the same on the dev branch: curl -L git.io/ioq3mac | sh 

So it installs the master with the broken link.

Is there another command for entering into the terminal for the dev branch?

**Comment by diegoulloao** [comment]
Oh, I forgot to replace the installation link. Check again `dev` branch instructions please

**Comment by QuakeDave** [comment]
The Installation works just fine now! Thank you very much for your fast response and buildt!

**Comment by mukabron** [comment]
As I saw in the updated ioQuake news post about HD Texture pack https://ioquake3.org/extras/replacement_content/
They have new sponsors and and new working link to the file: https://files.ioquake3.org/xcsv_hires.zip

**Comment by diegoulloao** [comment]
> As I saw in the updated ioQuake news post about HD Texture pack https://ioquake3.org/extras/replacement_content/ They have new sponsors and and new working link to the file: https://files.ioquake3.org/xcsv_hires.zip

I used to use that link before it went down.
https://github.com/diegoulloao/ioquake3-mac-install/blob/1b7627f520d7c2d6041e3dd0c598776f5e449c9c/install.sh#L41

I think file is exactly the same.
